### ISSUE TITLE
Unsetting outputs

### ISSUE THREAD

**Issue by MattEWeber** [icyphy/lingua-franca#119]
If a reactor has multiple reactions, we allow a later reaction to set an output to a different value than it was set to by an earlier reaction. But should we allow the later reaction to unset the value set to the output by an earlier reaction? In other words, can a reaction change a present output to absent?

Right now, the TypeScript target wouldn't allow this because the reaction epilogue check is.

```
if (send!== undefined) {
    __send.set(send);
}
```

If you tried to unset an output by assigning it the value `undefined` the `send!== undefined` check would fail. Plus in reactor.ts, the `set()` function doesn't accept undefined as a value.

I could change this to something like

```
if (send!== undefined) {
    __send.set(send);
} else {
    __send.unset(send);
}
```

and write an `unset` function.

Is this what we want?

**Comment by lhstrh** [comment]
Yes, this looks like a good solution to me.

**Comment by mew2ub** [comment]
Implementing `unset` is going to be a whole mess in TypeScript because we use push semantics for ports and reactions are added to the reaction queue as they are triggered. So if reaction 1 were to set a port, all the downstream reactors would already have added their reactions to the queue before reaction 2 had a chance to unset the port.

I can think of a few options:

1. The unset function removes reactions from the queue. This would take some additional bookkeeping to track exactly why every reaction on the queue was put there to ensure we don't remove reactions with multiple valid triggers.
2. Similar to 1, only we check if a reaction should still execute right before we call doReact on it.
3. Delay triggering reactions in reactors connected to downstream ports until all reactions in the current reactor that might unset downstream ports have executed.
4. Make it illegal to unset a port.

I prefer 3. Thoughts?

**Comment by lhstrh** [comment]
Yes, I anticipated this. This very much ties in with mutations, which might also require reactions to be disabled (e.g., because the event that triggered them came via a port that was disconnected at the same logical time). The problem is essentially the same, but option 3 does not address it. It may, however, limit parallelism, which is not a problem now but could become a problem when we introduce workers. Option 1 is tedious and probably inefficient. Option 2 should be straight-forward; the only thing that has to be checked is whether there is at least one trigger present. Option 4 I'm not sure how to enforce because one can always assign the value `undefined`.

To address the mutation problem, we could implement hierarchical connections using reactions, but this does not address the set/unset problem. Since it doesn't, I think option 2 would be better since it addresses both. We already have a FIXME for this in the code...

**Comment by lhstrh** [comment]
By the way, in the C target we don't currently provide `unset` functionality; once a reaction is triggered, it will execute. I'd suggest we get Edward's input on this before we go ahead.

**Comment by mew2ub** [comment]
The way to make it illegal to unset a port is just to leave it the way it is. The epilogue's

```
if (send!== undefined) {
    __send.set(send);
}
```

should handle it.

**Comment by lhstrh** [comment]
That's not forbidding it, that's ignoring it :-) I'm not sure that's a good idea. If you can make the assignment it doesn't make a whole lot a sense to then downstream find a value that is not `undefined`.

**Comment by edwardalee** [comment]
I don't understand the motivation for this.
Is this excess generality?
Do we have a reasonable use case?

**Comment by mew2ub** [comment]
@lhstrh Good point. You couldn't actually do it, but it wouldn't appear to be forbidden to a programmer. How about this for a runtime check?

```
if (send!== undefined ) {
    __send.set(send);
} else  if (__send_initial_value_at_start_of_reaction !== undefined) {
    throw new Error( "You can't do that!");
}
```

@edwardalee There's no particular use case, but this is something I think a reasonable programmer would expect to be able to do based on how writing TypeScript reactions works. You write to output ports by assigning values to local variables the value `undefined` signifies absent on a port. Why not try assigning `undefined` to an output port to "cancel" a previous output? We could either make this a valid thing to do or prohibit it.

**Comment by cmnrd** [comment]
I didn't think about this case before and checked again how things work in C++. It is possible to send a nullptr via `port.set(nullptr)`. This triggers all dependent reactions, but these reactions fill find no value. I particular `port.is_present()` returns `false`.

Now I am also wondering how to handle this case. Either `set()` should not accept a `nullptr` or it should untrigger all the reactions (which could be difficult).

**Comment by lhstrh** [comment]
In TypeScript, `undefined` means "absent" and `null` encodes a "pure event." In C++, `NULL` means "absent" so it should not be possible to trigger reactions in response to it. As per our discussion today, it is probably the easiest to forbid `NULL` as an input parameter to `set` in C++. In TypeScript, a value passed to `set` must be `Present`, which includes `null` but it obviously excludes `undefined`. The two implementations are consistent in the sense that they would not allow "absent" to trigger events.

**Comment by cmnrd** [comment]
I updated reactor-cpp to forbid setting a port to `nullptr` or scheduling an action with `nullptr`. The most common case, calling `set(nullptr)` or `schedule(nullptr)` directly, triggers a compile error. Since there are other ways for passing a nullptr (such as using an uninitialized smart pointer), `set()` and `schedule()` both perform an additional runtime check.
