### ISSUE TITLE
C++: Make use of the new target syntax and document it

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#122]

**Comment by lhstrh** [comment]
Noticed that I pushed some changes that condense most of the target property stuff into a single `enum` called `Targets`. We now also have a `TargetProperties` enum that not only lists the properties but also keeps track of which target supports which properties. I left a `FIXME` there suggestion that perhaps we'd want to rename `cmake_include` to `cmake-include` (since we have also have `no-compile`).

**Comment by cmnrd** [comment]
I am ok with renaming `cmake_include` to `cmake-include`. I actually did this today only to learn that the LF grammar does not support hyphens in target property names. To be more concrete, a hyphen is not allowed in an Xtext ID. The same goes for the `no-compile` property which I also cannot use. So I reverted back to the underscore for now.

**Comment by lhstrh** [comment]
I adjusted the grammar to allow hyphens in target property keys. I also reverted your commit that undid the `cmake_include` -> `cmake-include` change.

**Comment by cmnrd** [comment]
The C++ target now supports alost all available target properties. I also added two new properties `no-runtime-validation` and `build-type` that are sensible for the C++ target. See the [wiki](https://github.com/icyphy/lingua-franca/wiki/Writing-Reactors-in-C%EF%BC%8B%EF%BC%8B#the-c-target-specification) for more details.

The values allowed for `build-type` are the build type names as CMake defines them. It might make sense to use this property for other targets as well. In this case we might want to think about which general build types LF should support.
