### ISSUE TITLE
LF Grammar rules for time

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#123]
The following two reactor programs are valid according to the grammar and the validator, but to me they are at least unintuitive.

```
target C;
  main reactor HelloWorld {
      timer t(42, 1 sec);
      reaction(t) {=
          printf("Hello World.\n");
      =}
 }
```

```
target C;
  main reactor HelloWorld {
      timer t({=foo()=}, 1 sec);
      reaction(t) {=
          printf("Hello World.\n");
      =}
 }
```

It seems that the C code generator silently assumes that the given time is 0 if the value does not match the `<INT> <UNIT>` format. This appears strange to me. I think the grammar should be changed such that time values can only be either, `0`, a valid time with unit, or a parameter reference. This also applies to the other places where times are used such as delays and deadline. I think the only place where the grammar needs to allow arbitrary values is a parameter assignment.

I did not check how the TS target behaves in this case. The C++ target places whatever value it finds directly into the generated code, which might also lead to unexpected behavior.

**Comment by mew2ub** [comment]
I'm glad you brought this up because I wasn't handling the case of a `value` for a timer period or offset in the TypeScript generator at all. I think at least for TypeScript it's a workable solution to just dump whatever the value is into the generated code. That's because the TypeScript generator runs a type checker as part of compilation. The resulting error messages are pretty clear:

```
error TS2345: Argument of type '42' is not assignable to parameter of type '0 | TimeValue'.
```
and
```
error TS2304: Cannot find name 'foo'.
```

The types of a value (currently a literal) are `STRING | CODE | FLOAT | INT | NEGINT`. I'm okay prohibiting `STRING`, `FLOAT`, AND `NEGINT` in the grammar for timer offsets. I remember reading something in the docs about how targets are allowed to specify their own default time units which means we could potentially allow `INT`. But maybe we should consider changing that because I think that might just cause errors.

However, I think `CODE` might be okay to allow. What if the `foo()` function from your example were to be properly defined in a reactor preamble to return a time type?

**Comment by lhstrh** [comment]
@cmnrd: A `TimeOrValue` can also refer to a `Parameter` (the value of which can be a literal), so removing the problematic literals you point out from the `TimeOrValue` production isn't going to eliminate the problem entirely. In other words, the validator needs to do sanity checks on literals, anyway, if they are referenced via a parameter. There are other, similar checks pending on my to do list because they require the ability to resolve parameters (i.e., find out what their value is, taking in consideration that they can be overridden upon instantiation) -- I implemented this functionality as part of the instantiation tree that is used in `CGenerator` and my plan is to factor it out an make it available to the validator, diagram synthesis, and other code generators.

That said, I agree that the value should either be `0`, an integer with units, or a parameter that abides by the same constraints. We'll want these values to be accessible at compile time in order to perform safe-to-process analysis. Having to parse out or even evaluate target code to obtain the values would be very undesirable. I'm currently weighing the decision as to whether its better to change the grammar or simply perform checks in the validator. I'm leaning towards the latter because the former would substantially complicate the grammar.
