### ISSUE TITLE
What's the status of xtext/web, ide, sdk, ui, ui.tests, and updatesite?

### ISSUE THREAD

**Issue by mew2ub** [icyphy/lingua-franca#139]
Many of these haven't been touched in > 6 months. Has anyone done anything or have any plans for them recently?

Also, it looks like we have some Maven building set up (`xtext/pom.xml` and `xtext/maven.md`) but when I was digging into how `bin/build-lfc` works with gradle I didn't see how Maven is currently connected to our build or tests. The wiki has a section on (compiling and running tests with Maven)[https://github.com/icyphy/lingua-franca/wiki/downloading-and-building#Compiling-and-Running-Tests-Using-Maven]. Is this still current?

**Comment by lhstrh** [comment]
> Many of these haven't been touched in > 6 months. Has anyone done anything or have any plans for them recently?

I'll be working on `ide` soon to get syntax custom syntax highlighting for target language to work. Why?

> Also, it looks like we have some Maven building set up (`xtext/pom.xml` and `xtext/maven.md`) but when I was digging into how `bin/build-lfc` works with gradle I didn't see how Maven is currently connected to our build or tests.

You're right; it is not. Initially, Christopher Brooks got a Maven-based build setup to work, but it was very slow due to excessive downloading and other reasons that were difficult to comprehend. Gradle was much easier to deal with, so we switched. So far I've be reluctant to remove all the Maven-related configuration files because I vaguely recall that if we want to create an Eclipse plugin, we cannot use Gradle to build it.

> The wiki has a section on (compiling and running tests with Maven)[https://github.com/icyphy/lingua-franca/wiki/downloading-and-building#Compiling-and-Running-Tests-Using-Maven]. Is this still current?

It is not. We should probably remove it.

**Comment by cxbrooks** [comment]
Heh.  Oh yeah.  Maven.  Slow...  I remember it well, like the start of a bad detective story where the hero wakes up with their head stuck to the desk.  But I digress.

As per [compiling and running tests with Maven](https://github.com/icyphy/lingua-franca/wiki/downloading-and-building#Compiling-and-Running-Tests-Using-Maven)
I just checked and I with jdk-10.0.2, and the compile and verify worked.  I did
```
rm -rf ~/.m2
```
So that my Maven cache was empty so as to illustrate the pain of the first build.  I then did
```
git clone  https://github.com/icyphy/lingua-franca
cd lingua-franca/xtext/
time mvn compile
```
which took this amount of time:
```
real    7m13.896s
user    3m32.732s
sys     0m18.859s
```
Yes, maven downloads lots of things the first time and each successive time.

After running the above, if I then ran `time mvn compile` again,  I got:
```
real    0m51.617s
user    2m44.188s
sys     0m9.192s
```
Running `time mvn clean` yielded
```
real    0m18.258s
user    0m37.804s
sys     0m1.756s
```
and then `time mvn compile`, yielded:
```
real    0m55.360s
user    3m1.851s
sys     0m9.531s
```
There are various options, such as -o to work offline, see https://github.com/icyphy/lingua-franca/wiki/Maven-Notes

After `mvn clean`, `time mvn -o compile `yielded:
```
real    0m48.522s
user    2m50.895s
sys     0m9.376s
```
`time mvn verify` yielded
```
real    1m8.926s
user    3m20.815s
sys     0m11.367s
```
`time mvn -o verify` yielded:
```
real    0m57.936s
user    3m17.460s
sys     0m10.835s
```
`time  mvn -o test` yielded:
```
real    0m47.813s
user    2m48.708s
sys     0m9.309s
```

`mvn -o test -rf :org.icyphy.linguafranca.tests` used to work, but no longer does.  If the Maven support is going to stay in, then I could take a look.

I'm not sure if the above runs all the tests or not, someone would need to look.

I used maven to do release of (Triquetrum)[https://github.com/eclipse/triquetrum] in October 2019 and I believe that there is no other way, but things change, so maybe this is not true.

To build a release (what ever that is), try `mvn site`, which currently fails.  If there is interest in retaining support for Maven, then I could take a look at that, too

I have (notes about the Triquetrum release process)[https://wiki.eclipse.org/Triquetrum/Releng].  If you want to do a similar release for LF, I'd be happy to help.

**Comment by lhstrh** [comment]
Thanks, Christopher! My goal was to only preserve support for Maven for those entities that require it (we effectively don't use Maven at all right now). I forgot what the deal was exactly, but I'm pretty sure that (at the time, anyway) there existed no Gradle build support for the Eclipse plugin, which is why I left things the way they were for the time being, with a dormant Maven configuration next to an active Gradle configuration.

I'm still not sure why Matt raised this issue, because we're not near a first release stage yet, which is the time at which I was planning to sort these things out...

Anyways, good to know that we can count on your help with Maven!

**Comment by mew2ub** [comment]
Thanks Christopher and Marten. There's no deeper meaning to discern behind my question. I was curious what was going on with these parts of the repo I'd never interacted with.
