### ISSUE TITLE
TS benchmarks don't execute

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#151]
Here's the output from a successful compilation and failed run of one of the benchmarks:

```
[marten@yoga TS]$ lfc -r Big.lf 
Already up-to-date.
Generating code for: file:/home/marten/git/lingua-franca/benchmark/TS/Big.lf
******** filename: Big
******** sourceFile: /home/marten/git/lingua-franca/benchmark/TS/Big.lf
******** directory: /home/marten/git/lingua-franca/benchmark/TS
******** mode: STANDALONE
This project already has /home/marten/git/lingua-franca/benchmark/TS/package.json
This project already has /home/marten/git/lingua-franca/benchmark/TS/Big/tsconfig.json
This project already has /home/marten/git/lingua-franca/benchmark/TS/Big/babel.config.js
Type checking with command: /home/marten/git/lingua-franca/benchmark/TS/node_modules/typescript/bin/tsc
In directory: /home/marten/git/lingua-franca/benchmark/TS/Big
Executing command: /home/marten/git/lingua-franca/benchmark/TS/node_modules/typescript/bin/tsc
--- Standard output and error from command:
--- End of standard output and error.
Compiling with command: /home/marten/git/lingua-franca/benchmark/TS/node_modules/.bin/babel src --out-dir dist --extensions .ts
In directory: /home/marten/git/lingua-franca/benchmark/TS/Big
Executing command: /home/marten/git/lingua-franca/benchmark/TS/node_modules/.bin/babel src --out-dir dist --extensions .ts
--- Standard output and error from command:
Successfully compiled 10 files with Babel.
--- End of standard output and error.
SUCCESS (compiling generated TypeScript code)
Code generation finished.
[marten@yoga TS]$ node Big/dist/Big.js 
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'command-line-usage'
Require stack:
- /home/marten/git/lingua-franca/benchmark/TS/Big/dist/Big.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/marten/git/lingua-franca/benchmark/TS/Big/dist/Big.js:10:48)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/marten/git/lingua-franca/benchmark/TS/Big/dist/Big.js' ]
}
```

**Comment by mew2ub** [comment]
Hmm it compiles for me. Looking at your error message I'd guess you don't have the `command-line-usage` node module installed. Perhaps your package.json is out of date? Try deleting the package.json in your benchmarks directory and recompiling.

**Comment by lhstrh** [comment]
Yes, that worked. This, however, illustrates exactly what I meant by "not getting updates" being problematic (#120).

**Comment by mew2ub** [comment]
I believe the topic we were discussing in #120 was whether `npm install` should run every time you compile. Even if lfc were to do that, it wouldn't have fixed an out-of-date package.json. It just would have updated the old modules without getting the new ones. It wouldn't work either to refresh package.json with the newest default version in lib/TS when you run lfc because any custom modules you installed for a particular project listed in the old package.json would get deleted. It would be impossible to install new modules and have them "stick". So we may have to continue to live with manually resetting the existing package.json when new core modules are added to reactor-ts.

If we were to write a script to execute all the benchmarks in the directory, similar to bin/run-lf-tests, we could have that script automatically reset package.json before compilation. That could help prevent this from being a problem in the future, at least for benchmarks.

**Comment by lhstrh** [comment]
Ah, you're right, these are indeed separate issues. Semantic versioning of the package.json would help here (to report the problem rather than bluntly fail). It wouldn't be too often that the dependencies of reactor-ts change, however, so let's not worry about it for the time being...
