### ISSUE TITLE
Windows port is not working

### ISSUE THREAD

**Issue by lhy673542630** [icyphy/lingua-franca#153]
Hi, 
I used "action with values" in my code.
However, it show errors and doesn't compile. The error said "undefined reference to `schedule_int'"

![image](https://user-images.githubusercontent.com/48234895/80602463-461ee480-8a83-11ea-84d2-861ce1212878.png)

I also tried the demo code which uses "schedule_int" in Lingua Franca Wiki. It also didn't compile.
It also happened to "schedule_copy", I didn't test if "schedule_token" worked.
Could you please double check "schedule_int" and help me fix it?

Thank you very much!
Best regards

**Comment by edwardalee** [comment]
Hmm... Works for me. Here is a full test file:
```
target C;
reactor Source {
        output out:int*;
        logical action a:int;
        reaction(startup) -> a {=
            schedule_int(a, MSEC(200), 42);
        =}
        reaction(a) -> out {=
            set_token(out, a_token);
        =}
    }
reactor Print {
    input in:int*;
    reaction(in) {=
        printf("Received %d\n", *in);
    =}
}
main reactor Junk {
    s = new Source();
    p = new Print();
    s.out -> p.in;
}
```
Can you provide your full test file?

**Comment by lhy673542630** [comment]
Hi,
I have tried the code you provided. It is so weird that same error occurs.

Please have a look at the code below:
target C;

  main reactor HelloWorld 
  {
     logical action a:int;
    
     reaction(startup) -> a {=
        schedule_int(a, MSEC(100), 5);
    =}
      reaction (a) {=
      	printf("The value of the action is %d\n", a_value);  	
      =}
  }
  
  
  
It error it show is:
![image](https://user-images.githubusercontent.com/48234895/80686154-66e74880-8b1c-11ea-823f-6fde3f0b817a.png)

I am working on Windows and I am tried with Cygwin and Mingw. I still couldn't get rid of the error.

In addition, there is an error message in the LF IDE:
![image](https://user-images.githubusercontent.com/48234895/80686978-b1b59000-8b1d-11ea-97b6-908d541effa1.png)

Thanks a lot for your help!

Best regards

**Comment by edwardalee** [comment]
Ah, unfortunately, none of the developers is working on Windows, and it's possible that recent changes that we made to deal with PATH problems in Eclipse don't work in Windows out of the box. I don't have access to a Windows machine to try things out right now, so we could use your help to figure out how to make this work.

Can you try installing the bash shell in Cygwin to see whether that gets rid of the second problem?  The first problem is odd. Is your git clone up to date? In the src-gen directory that is created, there should be a reactor_common.c file that defines schedule_int. Is that file there? If not, then the code generator must be failing to copy into the src-gen directory. That file gets #included by the generated hw.c file.  A couple more things to try:

Run gcc by hand. In the directory where your .lf file is, try:
   gcc -O2 src-gen\hw.c -o bin\hw

Also, you could try running the command line compiler rather than having Eclipse generate the code:
  lfc hw.lf

If you could report what you see with these, maybe we can diagnose this.

**Comment by lhy673542630** [comment]
Hi,

Sorry for the late reply. I have try the ways that you suggested. However, it still doesn't work.
I will try to find out the reason (or I could move to Linux :)   )

Thank you very much!

**Comment by Soroosh129** [comment]
@lhy673542630, would you please verify if the problem persists with the latest commit? Commit 099dd27c7e1a0a4d70e6d0c054e518d50eba4390 should have fixed this issue on Windows.

**Comment by lhstrh** [comment]
Closing this issue since a fix has been provided. Feel free to re-open if the problem persists or reappears.
