### ISSUE TITLE
Comments before code blocks are not parsed correctly.

### ISSUE THREAD

**Issue by edwardalee** [icyphy/lingua-franca#161]
If you put a comment before a code block, then the parser fails. It seems that the parser swallows the first two characters of the comment (the '/*' or '//') and then leaves the rest. The code generator then produces invalid code.  Examples:
```
    output out: /* Comment */ {=bool=};
```
and
```
    reaction(in) -> out /* Comment */ {=
       ...
    =}
```

**Comment by cmnrd** [comment]
I might have an idea of what is going on here. It is only a guess, but I think Xtext attributes the comment to the AST node that it is currently building. In this case, it is the Code Block. Now, the code blocks are special in LF. Normally we work directly with the AST nodes and their attributes and thus don't sse this issue. But for the Code block, it works differently. I don't fully understand the mechanism behind this, but it appears to me that the `toText()` method used to get the target code as a string looks at the original part of LF code that Xtext used to build the AST node. This string contains the comment (which makes sense because no other rule consumes the comment). Now another problem arises. The toText method also processes the target code string and, in particular, it removes the '{=' delimiter. It does so naively by simply deleting the first 2 characters without checking the actual content.

I think there are two possible solutions to this issue:
1. Change the grammar rule such that there is an optional comment before the `{=` delimiter. Then the comment would be consumed already before Xtext moves on to build the Code AST node.
2. Embrace this as a future and include the comment in the generated code. We would only need to make the toText method smarter and search for the first occurence of `{=`.

**Comment by edwardalee** [comment]
OK, yes, this is what is happening: The comment is considered part of the code block.  So what is being passed to the parser to the code generator is this:
```
    /* comment */ {= ... =}
```
In ASTUtils.xtend, the toText() method was just doing
```
    str = str.substring(2, str.length - 2)
```
resulting in
     comment */ {= ... =}
```
I have fixed this, but found another problem.  ASTUtils.trimCodeBlock() removes blank lines at the start of a code block. Why?  This throws off the #line directives.  I've removed this feature.

**Comment by cmnrd** [comment]
There was no particular reason. Just thinking that white spaces are unnecessary. Thanks for fixing this!
