### ISSUE TITLE
Timing in Pipeline

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#166]
`Pipeline.lf` is now working, but notice the strange timing:

```
[marten@yoga C]$ bin/Pipeline 
---- Start execution at time Sun May 31 17:08:01 2020
---- plus 658004421 nanoseconds.
Received: 0
Received: 1
Received: 2
Received: 3
Received: 4
Received: 5
Received: 6
---- Elapsed logical time (in nsec): 2,000,000,000
---- Elapsed physical time (in nsec): 7,606,729,234
```

The Cpp version does not exhibit this lag.

**Comment by edwardalee** [comment]
If you set threads: 4, you get this:

EALMAC:C eal$ bin/Pipeline 
---- Start execution at time Sun May 31 18:28:08 2020
---- plus 948320000 nanoseconds.
Received: 0
Received: 1
Received: 2
Received: 3
Received: 4
Received: 5
Received: 6
Worker thread exited.
---- Elapsed logical time (in nsec): 2,000,000,000
---- Elapsed physical time (in nsec): 2,230,250,000

This shows it's using the cores to execute in parallel with near linear speedup.

**Comment by lhstrh** [comment]
Ah, that makes sense. No thread parameters were given in the Cpp test, however, so its thread allocation scheme appears to be different from the C runtime. @cmnrd could you comment on this?

**Comment by cmnrd** [comment]
Yes, there is a difference. Unlike in C, the number of threads is a purely dynamic property in the C++ target. There is no unthreaded version that avoids pthreads. If the number of threads is set to one, then no worker thread is created (everything gets executed inline by the scheduler), but pthreads is still required for mechanics like sleeping. Since there is no distinction between a threaded and an unthreaded version, I figured it would be reasonable to set the default number of threads simply to the number of hardware threads of the executing machine. This is what the C++ runtime currently does.

**Comment by lhstrh** [comment]
This default behavior makes sense to me. Does it still change the number of threads in accordance with the target property when it is set? It makes me wonder whether we should do the same in C (i.e., have the default number of threads match the number of cores, and use the single-threaded runtime only when `threads` is set to `1`. @edwardalee WDYT?

**Comment by edwardalee** [comment]
The unthreaded code still outperforms the threaded code by a considerable margin, so I'm not sure.  If we close that gap, then sure.

**Comment by lhstrh** [comment]
:+1:

**Comment by cmnrd** [comment]
> Does it still change the number of threads in accordance with the target property when it is set?

Yes. If the target property is set, then this is considered as the default value.
