### ISSUE TITLE
Printing while using "simulated sensors" based on ncurses

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#252]
Whenever `ncurses` is used, regular `printf` statements could interfere with program output. In a federated execution, remote reactors' `printf` output typically gets lost. Do we want to have a dedicated LF print facility that allows us to exercise more control and address these issues? If so, what should the API look like?

**Comment by edwardalee** [comment]
I just yesterday pushed a start toward this.  See util.h in the core library.

**Comment by lhstrh** [comment]
I noticed more progress in https://github.com/icyphy/lingua-franca/commit/cff1aecc649ac8a018cbd37af49149f2787bfbdd. Could we close this issue yet, or is there more work to be done?

**Comment by edwardalee** [comment]
This is done. In summary, almost all printing from the C runtime now goes through the utility functions in util.h/c. Those functions include a mechanism to register an alternative to the default (using printf). The sensor_simulator now registers such a function so that messages printed from the runtime do not mess up the ncurses UI.
