### ISSUE TITLE
feature request: get_elapsed_physical_time

### ISSUE THREAD

**Issue by schoeberl** [icyphy/lingua-franca#49]
For logical time we have get_logical_time and get_elapsed_logical_time. For physical time the elapsed value would be interesting as well. Comments?

**Comment by edwardalee** [comment]
I agree

Edward

------------
Edward A Lee
Professor
UC Berkeley

On Nov 12, 2019, at 11:17 AM, Martin Schoeberl <notifications@github.com>
wrote:

For logical time we have get_logical_time and get_elapsed_logical_time. For
physical time the elapsed value would be interesting as well. Comments?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/icyphy/lingua-franca/issues/49?email_source=notifications&email_token=ACA6ONWAD7MR3F2XMTEMIBLQTL6MPA5CNFSM4JMH2NA2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HYZITGQ>,
or unsubscribe

**Comment by schoeberl** [comment]
Ok, done.
