### ISSUE TITLE
run-lf-tests does not use the run command from the LF target specification

### ISSUE THREAD

**Issue by cmnrd** [icyphy/lingua-franca#54]
This is the main reason why all of the C++ target tests currently fail. `run-lf-tests` calls all test binaries with the comand line option `-timeout 1 sec`. This option, however, is not supported in the C++ target. The option there is called `--timeout` (with two dashes) and does not expect a separate unit. The reason for this is that the [CLI11](https://github.com/CLIUtils/CLI11) library that I use for parsing arguments only supports "standard compliant" arguments.

While we probably should have a discussion on if and how CLI arguments should be aligned between targets, I still think that the tests should respect the command line given in the LF target specification.

**Comment by edwardalee** [comment]
I have pushed a change in the C generator so that the generated code, by default, behaves according to the run option in the target directive. That is, if you do:
```
    target C (
        run = "bin/CountTest -timeout 3 sec -fast"
    );
```
then the default timeout will be 3 seconds. The timeout can be overridden by specifying some other value when invoking the program from the command line.  The -fast option cannot currently be overridden because we do not have a -slow option, but since -fast will eventually become unnecessary, I don't think we need to worry about this.

We can now remove the -timeout option from the run-lf-tests script as far as the C tests are concerned.

**Comment by cmnrd** [comment]
Closing this as it appears to be fixed in all the targets. I also removed the `--timeout` from the test script for C++. Note that the timeout is still overridden for C tests.
