### ISSUE TITLE
Dependency on `cmake`

### ISSUE THREAD

**Issue by lhstrh** [icyphy/lingua-franca#68]
The C++ code generator uses `cmake` in the build process. On Mac, `cmake` is put into `/opt/bin`, which is not on the default `PATH`, it turns out. The fix appears to be to add `opt/bin` to `/etc/paths`. We can improve error messages to make clear what the actual problem is, but we suspect that many Mac users will end up running into this issue. The question is: do we really need/want `cmake`?

**Comment by cmnrd** [comment]
I personally want cmake and I think we actually need it. As I see it, there are
two alternatives to cmake:

1. We could fall back to plain Makefiles
2. We could use another advanced build system (scons for instance)

Both options are bad in my opinion. Option 1 is bad because writing makefiles
is pain. It works well for small projects that should run on a specific
platform, but as soon as you want to support multiple compilers on multiple
platforms linking to different versions of the STL and potentially other
libraries, things become complex. Cmake solves this. Of course there are some
smaller problems here and there (as we had with MacOS), but once the
configuration works a rather simple cmake script allows you to build your
project on any of the major plarforms using any of the major C++ compilers.

I think option 2 is bad because switching the build system would only move the
dependency. I expect similar (if not worse) problems with any of the
alternatives I know of. The advantage of cmake is that it is widely used in
C++ projects. This means that a C++ developer usually has cmake
installed. Moreover it allows LF programms to easily link to other cmake
projects (See AsyncCallback.lf and AsyncCallback.cmake in C++ tests)

In my opinion, it is not too much to require that cmake is installed and
available in PATH. Most C++ programmers will have cmake installed anyway.

Couldn't we simply resolve the path issue by checking if cmake is available (or
if Eclipse is running on MacOS) and try to run /opt/bin/cmake if it is not?

**Comment by lhstrh** [comment]
We could manually add the directory where OSX installs `cmake` to the PATH variable given to the ProcessBuilder (if that dir exists). That shouldn't really get into the way of anything... What is the directory, Edward? Was is `/opt/bin` or `/opt/local/bin`?

**Comment by edwardalee** [comment]
I’m pushing changes to CppGenerator that “solve” the cmake problem on at least my Mac and that print out more informative messages.  However, now the generated code does not compile with make. ??? I don’t think I changed anything that would have affected that…

Note that in our coding style, we are using four spaces for indentation, not tabs. CppGenerator now has a mix, unfortunately. Can I replace all tabs with four spaces?

The output for HelloWorld now looks like this (with error messages from make):


Generating code for: platform:/resource/CppTests/HelloWorld.lf
******** filename: HelloWorld
******** sourceFile: /Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/HelloWorld.lf
******** directory: /Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp
******** mode: INTEGRATED
WARNING: cmake not found on PATH: /usr/bin:/bin:/usr/sbin:/sbin
Trying /opt/local/bin/cmake
--- In directory: /Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/build/HelloWorld
--- Running: /opt/local/bin/cmake -DCMAKE_INSTALL_PREFIX=/Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp -DREACTOR_CPP_BUILD_DIR=/Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/build/reactor-cpp /Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/src-gen/HelloWorld
------ Standard output from cmake command:
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/build/HelloWorld

------ End of standard output from cmake command.
--- In directory: /Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/build/HelloWorld
--- Running: make -j16 install
ERROR: make returns error code 2
ERROR: make reports errors:
/Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/src-gen/HelloWorld/main.cc:34:3: error: use of undeclared identifier 'CLI'
  CLI::App app("HelloWorld Reactor Program");
  ^
/Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/src-gen/HelloWorld/main.cc:37:3: error: use of undeclared identifier 'app'
  app.add_option("-t,--threads", threads, "the number of worker threads used by the scheduler", true);
  ^
/Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/src-gen/HelloWorld/main.cc:39:22: error: use of undeclared identifier 'app'
  auto opt_timeout = app.add_option("--timeout", timeout, "Number of seconds after which the execution is aborted");
                     ^
/Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/src-gen/HelloWorld/main.cc:41:3: error: use of undeclared identifier 'app'
  app.add_flag("-f,--fast", fast, "allow logical time to run faster than physical time"); 
  ^
/Users/eal/git/lingua-franca/xtext/org.icyphy.linguafranca/src/test/Cpp/src-gen/HelloWorld/main.cc:43:15: error: use of undeclared identifier 'app'
  CLI11_PARSE(app, argc, argv);
              ^
5 errors generated.
make[2]: *** [CMakeFiles/HelloWorld.dir/main.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/HelloWorld.dir/all] Error 2
make: *** [all] Error 2



Edward


——————
Edward A. Lee
Professor of the Graduate School
EECS, UC Berkeley
http://eecs.berkeley.edu/~eal

**Comment by cmnrd** [comment]
I am not sure what might cause this issue. I pushed a few changes that should make the build process
more robust and hopefully solve the issue. If the error persist, could you remove all the build files and try again with `make VERBOSE=1`? The output should give us a clue of what is going wrong.

> Note that in our coding style, we are using four spaces for indentation, not tabs. CppGenerator now has a mix, unfortunately. Can I replace all tabs with four spaces?

Oh, I was not aware of that. I fixed this already. I was using the auto formatter of eclipse. Is there a formatter configuration that I should load?

**Comment by edwardalee** [comment]
OK, good. The cmake infinite loop is gone.

To set up Eclipse for our coding style, the instructions from here:


https://ptolemy.berkeley.edu/ptolemyII/ptII8.1/ptII/doc/coding/eclipse.htm#Preferences


say:

4. Ptolemy II source files are worked on by many people with different editors. Unfortunately, different text editors interpret tab characters differently, so it is best to use spaces rather than tabs. 
Sadly, the Eclipse developers have chosen to use tabs as spaces, so you must adjust the Eclipse Java Formatter if you plan on contributing code to the Ptolemy II tree. 
Also, it is best if files end with new line characters, so that we can run line oriented scripts on them. 
In addition, we currently do not want the Eclipse Formatter to format comments. We hope to change this policy in the future. 
We handle these changes together:
* While still in the preferences window 
(Mac OS X: Eclipse | Preferences) 
(Windows: Window | Preferences)
    * Go to Java | Code Style | Formatter and click New
    * In the "New Profile" Window, for the Profile name, enter "Ptolemy II" Under "Initialize settings with the following profile", select "Java Conventions [built-in]" (We use Java Conventions over the "Eclipse" setting because the Eclipse style uses tabs.) Then hit OK
    * Under the "Indentation" tab, change the Tab policy to "Spaces only". 
    * Under the "New Lines" tab, select "at end of file"
    * Under the "Comments" tab, unselect "Enable Javadoc comment formatting" unselect "Enable block comment formatting", otherwise the block comments that have  ...  get changed. Unselect "Enable line comment formatting", otherwise the headers for public methods etc. get changed.
    * Click OK.
* In the Preferences Window, click Apply.

**Comment by lhstrh** [comment]
On the coding style: on thing that I've always disliked about in Ptolemy is the strange way we format block comments. E.g.:
```
    /** Some comment written here.
     *  Two spaces and more comments.
     */
```
I've never seen this anywhere else, and I don't think it looks so good. Can we just do the following?
```
    /** 
     * Some comment written here.
     * Single space and more comments.
     */
```
I'd be happy to write a wiki section on coding style and share a ready-to-use Eclipse auto-formatter...

**Comment by edwardalee** [comment]
OK with me.
