### ISSUE TITLE
Targets, Hosts, and Distributed Execution

### ISSUE THREAD

**Issue by edwardalee** [icyphy/lingua-franca#89]
I have started a wiki page addressing big issues including how target options should be defined, how command-line options should be specified, and, biggest of all, how distributed execution is specified and implemented.   Please take a look at the [Targets, Hosts, and Distributed Execution](https://github.com/icyphy/lingua-franca/wiki/Targets,-Hosts,-and-Distributed-Execution) page.

Of particular near-term interest may be the [subsection here on command-line options](https://github.com/icyphy/lingua-franca/wiki/Targets,-Hosts,-and-Distributed-Execution#command-line). Do you agree with the strategy here? I would like to use this issue to discuss.

**Comment by lhstrh** [comment]
I will go read this a lot more thoroughly in order to provide detailed feedback, but the first thing I wanted to comment on is the syntax for target options. I agree that JSON is too verbose with all the quotes, but for such a simple thing as this (as pointed out earlier by Martin and Christian earlier regarding our testing configuration) we should not invent our own syntax. 

Also, we might want to import target properties from a file rather than specify them in the header of the `.lf` file, and it would be nice if the syntax were identical between the two (i.e., you could just copy target options into a separate file, import it, and be done with it). If would be nice if we could name that file `<something>.<extension of some well-known format>`.

I've noticed that what you wrote _almost is_ valid YAML. Here's the same info with some tweaks so that it _is_ valid YAML:
```
target: C
options: {
  compile: "-O2",
  fast: true,
  hosts: [
    {name: X, address: localhost, ports: 15050, reactors: [a, b], timeout: 10 secs},
    {name: Y, address: localhost, ports: 15050, reactors: [c], threads: 1},
  ]
  keepalive: true,
  threads: 4,
  timeout: 10 secs,
}
```

**Comment by edwardalee** [comment]
How about if a target specification has one of the two following forms:

target C path_to_file.yaml;

or

target C {
   contents as above in YAML syntax
};

(with the final semicolon being optional, as is typical in Java, C, C++.)

**Comment by lhstrh** [comment]
I like your proposal because it is easy to implement, but it also makes it difficult to include a base configuration and do small overrides; in that situation (which I expect will be fairly common) one would have to 1) write a separate YAML file for each configuration that is slightly different or 2) copy the entire configuration into the body of the LF source and adjust it. Both alternatives impede reuse.

We could also do something like this:

```
target C {
  include: path_to_file.yaml # Note that this include statement is _also_ valid YAML.
  # Contents as above.
};
```

This requires a little bit more work on our end (we'll have to follow links to included files are recursively build the resulting configuration), but it also reduces the syntax to a single form and augments the configuration with includes, something that YAML does not have as a built-in feature.

**Comment by edwardalee** [comment]
Sounds reasonable to me.

**Comment by mew2ub** [comment]
It occurred to me when you brought up the target specification during our conversation today that more information than is currently shown in the example target specification will be needed to compile programs for multiple machines. If code generation is intended to produce multiple executables meant to run on different architectures, the specification will need to have more options to specify multiple compilers and all the options involved in cross compiling.

Since generated JavaScript doesn't need to be cross compiled, It may be easier to work through examples for distributed execution first with the TS target instead of the C target.

**Comment by edwardalee** [comment]
Nevertheless, I think you are right that the TS target may be a better first test of this…

——————
Edward A. Lee
Professor of the Graduate School
EECS, UC Berkeley
http://eecs.berkeley.edu/~eal

**Comment by edwardalee** [comment]
This is a good point. However, I think the sample I showed actually does allow for this, as long as the target parameters allow for it.
Any target parameter can be overridden for any of the hosts.

Edward

———————
Edward A. Lee
Professor of the Graduate School
EECS, UC Berkeley
http://eecs.berkeley.edu/~eal

**Comment by edwardalee** [comment]
I have implemented this new syntax for the C target, with some exceptions. The YAML syntax for comments, which are preceded by '#', is not supported. Instead, `//` and `/* ... */` are supported. Also, the C target does not yet implement importing an external YAML file.  For now, the C target still supports the legacy syntax. The validator in Eclipse will give a warning when using the legacy syntax.

We will need to change the TS and Cpp targets to use this YAML syntax. Volunteers?

**Comment by mew2ub** [comment]
I'll do it for the TS target.

**Comment by edwardalee** [comment]
I have updated the C++ target to support the new target properties syntax. There are some issues, however (not new):

The --timeout command-line option seems to have a different meaning in this target than the C target. In the C target, it means the **logical time** at which to stop execution. In Cpp, it seems to just kill the process after some number of seconds has elapsed.

Also, the "run" target property can specify --timeout, but this is ignored. The generated code runs forever.

**Comment by mew2ub** [comment]
I just updated the TS target and the TS tests. The TS code generator now supports both the old and the new syntax. So far the only supported properties are "keepalive" and "timeout", but I'm going to be working on some more in the near future.

**Comment by cmnrd** [comment]
> The --timeout command-line option seems to have a different meaning in this target than the C target. In the C target, it means the logical time at which to stop execution. In Cpp, it seems to just kill the process after some number of seconds has elapsed.

This is the same in the C++ target. It is implemented sucht that the code generator defines a reactor with a timer that has an offset equal to the timeout. The reaction to this timer simply calls a function that performs the synchronous shutdown. However, there seems to be something wrong with the implementation (see #107). Maybe this problem also explains your observation.

**Comment by lhstrh** [comment]
Both links in OP are broken and all issues discussed here seem to have been addresses? Please reopen if I overlooked something. Closing...
